# Generated by Django 3.2.1 on 2021-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persian_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
