# Generated by Django 3.2.1 on 2021-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_persian_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persian_username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
