# Generated by Django 3.2.1 on 2021-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_persian_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translator',
            name='book_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
