# Generated by Django 3.2.1 on 2021-07-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('rate', models.FloatField(default=0.0)),
                ('publication_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.author')),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.translator')),
            ],
        ),
    ]
