# Generated by Django 3.2.1 on 2021-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
